export const API_BASE_URL = 'https://jsonmockserver.vercel.app/api/shopping/furniture';
export const RUPEE = '₹';
export const MY_CART = 'MY CART';
export const MY_WISHLIST = 'MY WISHLIST';
export const ADVERTISEMENT_HEADING = 'Your Home, With Love';
export const ADVERTISEMENT_SUB_HEADING = 'Come, Choose from millions of products';
export const SITBACK = 'SITBACK';
export const USER = 'Nijin Vinodan';
export const COPYRIGHTS = 'COPYRIGHTS 2023';
export const SHOP_NOW = 'SHOP NOW';
export const NOT_FOUND_ERROR = '404 Not Found';
export const NOT_FOUND_ERROR_DESCRIPTION = "Oops! The page you're looking for doesn't exist.";
export const QUANTITY = "Quantity: ";
export const ADD_TO_CART = "ADD TO CART";
export const ADD_TO_WISHLIST = "ADD TO WISHLIST";
export const TOTAL_AMOUNT = "TOTAL AMOUNT:";
export const PLACE_ORDER = "PLACE ORDER";
export const EMPTY_WISHLIST_MSG = "Your Wishlist is Empty...!";
export const EMPTY_CART_MSG = "Your Cart is Empty...!";
export const CART_NOT_AVAILABLE = "Cart is not available."
export const ORDER_CONFIRMATION = "Order Confirmation"
export const ORDER_CONFIRMATION_MSG = "Thank you for Shopping with us.The items will be deievered within 7 days."